### ISSUE TITLE
Technical Concepts of Brick

### ISSUE THREAD

**Issue by shreyasnagare** [BrickSchema/brick-website#23]
Add a page that explains the core concepts of Brick in depth.

**Comment by jbkoh** [comment]
Pushed here: ab5e8d7f23a0c6174e1cc3493d346854d960f3fc but hasn't been tested because I couldn't run it. (It didn't show any pages when I access ``http://xxx.xxx.xxx.xx`` or ``http://xxx.xxx.xxx.xx/#home``)

I will coordinate with @shreyasnagare tomorrow to test the page. I still need to add some contents too.
