### ISSUE TITLE
Creating docs

### ISSUE THREAD

**Issue by trettigIO** [BrickSchema/brick-website#72]
I wanted do create the docs of yours in order to get a better understanding how BRICKS works.
I used the recommended site:
https://shreyasnagare.github.io/rdf2docs/
and choosed the Version over the drag & drop and wanted to load the docs, but nothing happend except a loading bar appears. After the loading bar is finnished nothing happends.
It is possible to get a pdf-version of your docs.

In order to bring a little bit of context to this.
My name is Tobias Rettig an I'm working at aedifion (https://www.aedifion.com/). We offer a manufacturer-neutral IoT platform for building automation and technical building equipment. Therefore we collect a lot of data and we are looking for ways to contextualize the data.
Hence I'm not the most tech guy in the world I hoped that reading your docs will help me to understand how we could implement BRICKS for our customers and don't have to read the whole RDF Documentation for example.

For direct contact
M +49 151 27255679
trettig@aedifion.com

Thanks for the help!!!

**Comment by gtfierro** [comment]
Hi @trettigIO 

The more complete documentation of Brick concepts is located at https://brickschema.org/ontology/1.1 and some resources on how to get started using Brick are located at https://brickschema.org/get-started . There are no PDF versions available yet, but those links should at least work. Can you tell me where you found the pointer to https://shreyasnagare.github.io/rdf2docs/? We should probably remove that link because it doesn't seem to be working. 

I saw your email and I'll respond more in detail there

**Comment by trettigIO** [comment]
Hi @gtfierro 

Thank you for your fast response.
I found the link on your website under tools, then clicking on your BrickDocs, and than the screenshot site opens. When you click on website the described link pop up.
![grafik](https://user-images.githubusercontent.com/63038396/78330232-cab13c80-7583-11ea-82a2-eaec7cc000a8.png)
Thanks for the e-mail I will respond to the e-mail.

**Comment by gtfierro** [comment]
Many thanks for finding the broken link and thanks to @shreyasnagare  for fixing it so quickly! 

I'll close this issue for now
